### ISSUE TITLE
Fix the integration job

### ISSUE THREAD

**Issue by buep** [Praqma/file-pattern-scanner#3]
Currently the integration job isn't running the tests. In #1 I created a build and delivery pipeline, but we have never had a build slave that could run the jobs - we need to fix the issue.

Fix the integration job so it runs the tests.

**Comment by buep** [comment]
http://code.praqma.net/ci/view/All/job/file-patern-scanner_seedjob/

**Comment by buep** [comment]
@praqma-thi this slave was supposed to be dedicated for this project... it was a try to get things working: https://sites.google.com/a/praqma.net/it-administration/hq-infrastructure/virtualization/jenkinsubuntu16

**Comment by praqma-thi** [comment]
Integration job was vaporized a while ago.
Project is currently stable, we'll leave things as they are until development starts anew.
